/**
* This file was auto-generated by the Titanium Module SDK helper for Android
* Appcelerator Titanium Mobile
* Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
* Licensed under the terms of the Apache Public License
* Please see the LICENSE included with this distribution for details.
*
*/
package tv.harukaze.ti.nend.android;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.view.TiUIView;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.kroll.KrollDict;

import android.util.Log;
import android.view.Gravity;
import net.nend.android.NendAdView;
import net.nend.android.NendAdListener;

public class AdView extends TiUIView implements NendAdListener
{
    private NendAdView nendAdView =null;

    // Constructor
    public AdView(final TiViewProxy proxy) {
        super(proxy);
    }

    @Override
    public void processProperties(KrollDict d){
        super.processProperties(d);
        if( nendAdView == null ){
            int spotId = TiConvert.toInt(d, "spotID");
            String nendId = TiConvert.toString(d, "nendID");
            nendAdView = new NendAdView(TiApplication.getInstance().getApplicationContext(), spotId, nendId);
            nendAdView.setListener(this);
            nendAdView.setGravity(Gravity.CENTER);
            setNativeView(nendAdView);
        }
    }
    
    public void pauseAd(){
        nendAdView.pause();
    }
    
    public void resumeAd(){
        nendAdView.resume();
    }

    @Override
    public void onFailedToReceiveAd(NendAdView arg0) {
        proxy.fireEvent("error", null);
    }

    @Override
    public void onReceiveAd(NendAdView arg0) {
        proxy.fireEvent("load", null);
    }
}
